### Name: Limcangco, Jared Joaquin M.

### Section: 2ECE-B

###

### Programming Problems

######

In [107]:
import numpy as np   # Numpy is first imported as np in order for its functions to be used through the whole assignment.

#### A. Reproducible Normalization Problem

In [112]:
np.random.seed(2112)                                # Sets random seed to 2112 for random values each time.
X = np.random.randint(10, 101, size=(5, 5))         # Creates a 5x5 array that generates random values from 10 - 100.
X

array([[48, 11, 15, 67, 21],
       [11, 41, 13, 66, 24],
       [71, 79, 53, 67, 70],
       [77, 35, 91, 19, 96],
       [35, 54, 37, 41, 17]])

In [113]:
X_mean = X.mean()                            # Calculates mean of all values in X.
X_std = X.std()                              # Calculates population standard deviation of all values in X.
X_normalized = (X - X_mean) / X_std          # Normalizes each value using mean and std.
X_normalized

array([[ 0.06340841, -1.36714726, -1.2124926 ,  0.79801809, -0.98051059],
       [-1.36714726, -0.20723725, -1.28981993,  0.75935442, -0.86451959],
       [ 0.95267275,  1.26198209,  0.25672675,  0.79801809,  0.91400909],
       [ 1.18465476, -0.43921926,  1.72594609, -1.05783793,  1.91926443],
       [-0.43921926,  0.29539042, -0.36189192, -0.20723725, -1.13516526]])

In [114]:
print('X:')                                           # Displays the original array.
print(X)
print('X_normalized:')                                # Displays the normalized array.
print(X_normalized)
print('Mean of X_normalized:')                        # Calculates the mean.
print(X_normalized.mean())
print('Standard deviation of X_normalized:')          # Calculates the population standard deviation.
print(X_normalized.std())

X:
[[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]
X_normalized:
[[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]
Mean of X_normalized:
0.0
Standard deviation of X_normalized:
0.9999999999999999


In [115]:
np.save('X_normalized.npy', X_normalized)          # Saves the normalized array as the npy. file.

#### B. Cubes Divisible By 4 Problem

In [116]:
C = np.arange(1, 101) ** 3          # Creates first 100 values and cubes.
C = C.reshape(10, 10)               # Reshapes cubed values into 10x10 array.
C

array([[      1,       8,      27,      64,     125,     216,     343,
            512,     729,    1000],
       [   1331,    1728,    2197,    2744,    3375,    4096,    4913,
           5832,    6859,    8000],
       [   9261,   10648,   12167,   13824,   15625,   17576,   19683,
          21952,   24389,   27000],
       [  29791,   32768,   35937,   39304,   42875,   46656,   50653,
          54872,   59319,   64000],
       [  68921,   74088,   79507,   85184,   91125,   97336,  103823,
         110592,  117649,  125000],
       [ 132651,  140608,  148877,  157464,  166375,  175616,  185193,
         195112,  205379,  216000],
       [ 226981,  238328,  250047,  262144,  274625,  287496,  300763,
         314432,  328509,  343000],
       [ 357911,  373248,  389017,  405224,  421875,  438976,  456533,
         474552,  493039,  512000],
       [ 531441,  551368,  571787,  592704,  614125,  636056,  658503,
         681472,  704969,  729000],
       [ 753571,  778688,  804357,  8

In [117]:
div_by_4 = C[C % 4 == 0]          # Selects values divisible by 4.
div_by_4

array([      8,      64,     216,     512,    1000,    1728,    2744,
          4096,    5832,    8000,   10648,   13824,   17576,   21952,
         27000,   32768,   39304,   46656,   54872,   64000,   74088,
         85184,   97336,  110592,  125000,  140608,  157464,  175616,
        195112,  216000,  238328,  262144,  287496,  314432,  343000,
        373248,  405224,  438976,  474552,  512000,  551368,  592704,
        636056,  681472,  729000,  778688,  830584,  884736,  941192,
       1000000], dtype=int32)

In [119]:
print('Shape of C:')                     # Displays dimensions for the array.
print(C.shape)
print('div_by_4:')                       # Displays values divisible by 4.
print(div_by_4)
print('Number of selected elements:')    # Displays the number of selected values.
print(div_by_4.size)

Shape of C:
(10, 10)
div_by_4:
[      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]
Number of selected elements:
50


In [121]:
np.save('div_by_4.npy', div_by_4)  # Saves the values as the npy. file.

#### C. Above-Mean Squares Problem

In [122]:
S = np.arange(1, 37)**2  # Creates first 36 values and squares.
S = S.reshape(6, 6)      # Reshapes squared values into 6x6 array.
S

array([[   1,    4,    9,   16,   25,   36],
       [  49,   64,   81,  100,  121,  144],
       [ 169,  196,  225,  256,  289,  324],
       [ 361,  400,  441,  484,  529,  576],
       [ 625,  676,  729,  784,  841,  900],
       [ 961, 1024, 1089, 1156, 1225, 1296]])

In [123]:
S_mean = S.mean()        # Calculates mean of all values.
S_mean

np.float64(450.1666666666667)

In [124]:
above_mean = S[S > S_mean]    # Selects values that are greater than the mean.
above_mean

array([ 484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296])

In [125]:
print('S:')                                     # Displays the array.
print(S)
print('S_mean:')                                # Displays the mean.
print(S_mean)
print('above_mean:')                            # Displays values greater than the mean.
print(above_mean)
print('Number of selected elements:')           # Displays number of selected values.
print(above_mean.size)

S:
[[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]
S_mean:
450.1666666666667
above_mean:
[ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]
Number of selected elements:
15


In [126]:
np.save('above_mean.npy', above_mean)        # Saves selected values as the npy. file.

### Final Results

In [127]:
print('X_normalized.npy:')
print(np.load('X_normalized.npy'))

print('div_by_4.npy:')
print(np.load('div_by_4.npy'))

print('above_mean.npy:')
print(np.load('above_mean.npy'))

X_normalized.npy:
[[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]
div_by_4.npy:
[      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]
above_mean.npy:
[ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]
